### ISSUE TITLE
Track current authenticated user ID

### ISSUE THREAD

**Issue by DeftNerd** [ConsoleTVs/Links#3]
The ```Links::track()``` feature built into a default layout is very valuable but I think it would be awesome if it could optionally associate the entry with a User model object. 

In the migration table, you can add a user_id field that's nullable and if the user is logged in, fill in the user_id using ```Auth::user()->id``` as long as ```Auth::check()``` returns TRUE. 

That way you can log all the access that occurs, but if a user is logged into a web app, it'll associate the log entry with the user. The Link model could even have the relationship created so it's easy to associate with the default Users model.

**Comment by ConsoleTVs** [comment]
Will think about it, thanks!
